name: Deploy Go Application

on:
    push:
        branches:
          - master

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "PORT=${{ secrets.PORT }}" >> .env
            - name: Create .env file
              run: echo "PORT=${{ secrets.DB_URL }}" >> .env
            - name: Create .env file
              run: echo "PORT=${{ secrets.SECRET }}" >> .env
            - name: Create .env file
              run: echo "PORT=${{ secrets.AWS_REGION }}" >> .env
            - name: Create .env file
              run: echo "PORT=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            - name: Create .env file
              run: echo "PORT=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            - name: Build docker image
              run: docker build -t muhammadandres/manajemen-tugas-app .
            - name: Push image to docker hub
              run: docker push muhammadandres/manajemen-tugas-app:latest
              
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull docker image
              run: docker pull muhammadandres/manajemen-tugas-app:latest
            - name: Delete old container
              run: docker rm -f manajemen-tugas-container
            - name: Run docker container          
              run: docker run -d -p 6060:6060 --name manajemen-tugas-container muhammadandres/manajemen-tugas-app